name: studysmartmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  permission_handler: ^11.3.1
  mobile_scanner: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: LeeSeoYun
      fonts:
        - asset: assets/fonts/leeseoyun.ttf

  assets:
    - assets/icons/ssm_logo.png
    - assets/buttons/kakao_login_button.png